# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jam < Formula
  desc "Coordinate Claude Code sessions with remote agents and humans on the Band platform"
  homepage "https://github.com/ed-lepedus-thenvoi/jam"
  version "0.1.13"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ed-lepedus-thenvoi/jam/releases/download/v0.1.13/jam_0.1.13_darwin_amd64.tar.gz"
      sha256 "919d30cd681e37fef7846b93824dabad54a7c2f56468c275378d0b992f2e4e75"

      define_method(:install) do
        bin.install "jam"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ed-lepedus-thenvoi/jam/releases/download/v0.1.13/jam_0.1.13_darwin_arm64.tar.gz"
      sha256 "820f1cf9cc6c04fcd30751149d0f837ee05ed5cea5fbf43fc7364e7c7815c05a"

      define_method(:install) do
        bin.install "jam"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ed-lepedus-thenvoi/jam/releases/download/v0.1.13/jam_0.1.13_linux_amd64.tar.gz"
      sha256 "5dd4c04eacf866d3e5576c33033aefc64d0f56f32a1d94d3f60b49eba2824ee0"
      define_method(:install) do
        bin.install "jam"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ed-lepedus-thenvoi/jam/releases/download/v0.1.13/jam_0.1.13_linux_arm64.tar.gz"
      sha256 "cba472fb9609fb8fb3a8697c78beeaa0c46cbb1cb8cb505c84bc1cdee72494c1"
      define_method(:install) do
        bin.install "jam"
      end
    end
  end

  test do
    assert_match "Coordinate Claude Code sessions", shell_output("#{bin}/jam --help")
  end
end
